url: http://ostholstein.freifunk.net/

community:
  # Metadata
  name: "Ostholstein"
  meta: "Schleswig-Holstein"
  country: "DE"

  # Custom URLs
  url_wiki:  "http://luebeck.freifunk.net/wiki/Ostholstein"
  url_webchat: "https://riot.eclabs.de/#/room/#ffoh:matrix.eclabs.de"
  url_geomap: "/map2/geomap.html"
  url_graph: "/map2/graph.html"
  url_nodelist: "/map2/nodes.list"
  url_mailman: "http://lists.ostholstein.freifunk.net/mailman/listinfo/list"
  url_logo: "/images/ffoh-logo.png"

  # Mail Contacts
  mail_info: "info@ostholstein.freifunk.net"
  mail_keys: "keys@ostholstein.freifunk.net"
  #mail_discussion: "discussion@ostholstein.freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffoh", "space@10.254.254.254"] # Optional
  #twitter: "FreifunkOstholstein" # Optional
  #irc: "#ffoh"

  # GPS
  geo_lat: 54.010162934330765 
  geo_lon: 10.79681396484375

firmware:
  base: "http://ostholstein.freifunk.net/firmware/experimental/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/smoe/site-ffoh"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"

tld:
  label: "ffoh"
  ns:
    - "10.135.0.8"
    - "fd73:111:e824::1:1"
    - "10.135.0.16"
    - "fd73:111:e824::1:2"
    - "10.135.0.24"
    - "fd73:111:e824::1:3"
    - "10.135.0.32"
    - "fd73:111:e824::1:4"
